// packages/solidstart/src/routes/filter.tsx
import { createSignal, createMemo, For, Show, onMount } from "solid-js";
import type { Product, Category, ApiResponse } from "@benchmark/data";
import { A } from "@solidjs/router";

const API_URL = import.meta.env["VITE_API_URL"] ?? "http://localhost:3000";

const CATEGORIES: Category[] = [
  "Electronics",
  "Clothing",
  "Books",
  "Home & Garden",
  "Sports",
  "Toys",
  "Food & Beverage",
  "Beauty",
];

type SortKey = "name" | "price-asc" | "price-desc" | "rating";

export default function FilterPage() {
  const [products, setProducts] = createSignal<Product[]>([]);
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal<string | null>(null);
  const [selectedCategories, setSelectedCategories] = createSignal<Set<Category>>(new Set());
  const [minPrice, setMinPrice] = createSignal(0);
  const [maxPrice, setMaxPrice] = createSignal(1000);
  const [minRating, setMinRating] = createSignal(0);
  const [sortKey, setSortKey] = createSignal<SortKey>("name");

  onMount(async () => {
    try {
      const res = await fetch(`${API_URL}/products`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = (await res.json()) as ApiResponse<Product[]>;
      setProducts(json.data);
      const prices = json.data.map((p) => p.price);
      setMaxPrice(Math.ceil(Math.max(...prices)));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load products");
    } finally {
      setLoading(false);
    }
  });

  const toggleCategory = (cat: Category) => {
    setSelectedCategories((prev: Set<Category>) => {
      const next = new Set<Category>(prev);
      if (next.has(cat)) {
        next.delete(cat);
      } else {
        next.add(cat);
      }
      return next;
    });
  };

  const filtered = createMemo(() => {
    return products()
      .filter((p) => {
        if (selectedCategories().size > 0 && !selectedCategories().has(p.category))
          return false;
        if (p.price < minPrice() || p.price > maxPrice()) return false;
        if (p.rating < minRating()) return false;
        return true;
      })
      .sort((a, b) => {
        switch (sortKey()) {
          case "price-asc":
            return a.price - b.price;
          case "price-desc":
            return b.price - a.price;
          case "rating":
            return b.rating - a.rating;
          default:
            return a.name.localeCompare(b.name);
        }
      });
  });

  const resetFilters = () => {
    setSelectedCategories(new Set<Category>());
    setMinPrice(0);
    const prices = products().map((p) => p.price);
    setMaxPrice(prices.length > 0 ? Math.ceil(Math.max(...prices)) : 1000);
    setMinRating(0);
  };

  return (
    <div>
      <h1 class="text-3xl font-bold text-gray-900 mb-8">Filter Products</h1>
      <Show
        when={!loading()}
        fallback={
          <div class="flex h-64 items-center justify-center">
            <div class="h-8 w-8 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" />
          </div>
        }
      >
        <Show when={!error()} fallback={
          <div class="rounded-lg bg-red-50 p-6 text-center">
            <p class="text-sm font-medium text-red-600">Error: {error()}</p>
          </div>
        }>
          <div class="flex flex-col gap-6 lg:flex-row">
            {/* Sidebar filters */}
            <aside class="w-full shrink-0 lg:w-64">
              <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                <h2 class="text-base font-semibold text-gray-900 mb-4">Filters</h2>

                {/* Categories */}
                <div class="mb-6">
                  <h3 class="text-sm font-medium text-gray-700 mb-3">Category</h3>
                  <div class="flex flex-col gap-2">
                    <For each={CATEGORIES}>
                      {(cat) => (
                        <label class="flex items-center gap-2 cursor-pointer">
                          <input
                            type="checkbox"
                            checked={selectedCategories().has(cat)}
                            onChange={() => toggleCategory(cat)}
                            class="h-4 w-4 rounded border-gray-300 text-blue-600"
                          />
                          <span class="text-sm text-gray-600">{cat}</span>
                        </label>
                      )}
                    </For>
                  </div>
                </div>

                {/* Price Range */}
                <div class="mb-6">
                  <h3 class="text-sm font-medium text-gray-700 mb-3">Price Range</h3>
                  <div class="flex flex-col gap-3">
                    <div>
                      <label class="text-xs text-gray-500">Min: ${minPrice()}</label>
                      <input
                        type="range"
                        min={0}
                        max={maxPrice()}
                        value={minPrice()}
                        onInput={(e) => setMinPrice(Number(e.currentTarget.value))}
                        class="w-full accent-blue-600"
                      />
                    </div>
                    <div>
                      <label class="text-xs text-gray-500">Max: ${maxPrice()}</label>
                      <input
                        type="range"
                        min={0}
                        max={maxPrice()}
                        value={maxPrice()}
                        onInput={(e) => setMaxPrice(Number(e.currentTarget.value))}
                        class="w-full accent-blue-600"
                      />
                    </div>
                  </div>
                </div>

                {/* Min Rating */}
                <div class="mb-6">
                  <h3 class="text-sm font-medium text-gray-700 mb-3">
                    Min Rating: {minRating().toFixed(1)}
                  </h3>
                  <input
                    type="range"
                    min={0}
                    max={5}
                    step={0.5}
                    value={minRating()}
                    onInput={(e) => setMinRating(Number(e.currentTarget.value))}
                    class="w-full accent-blue-600"
                  />
                  <div class="flex justify-between text-xs text-gray-400 mt-1">
                    <span>0</span>
                    <span>5</span>
                  </div>
                </div>

                {/* Reset */}
                <button
                  onClick={resetFilters}
                  class="w-full rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-50 transition-colors"
                >
                  Reset Filters
                </button>
              </div>
            </aside>

            {/* Results */}
            <div class="flex-1 min-w-0">
              <div class="flex items-center justify-between mb-4">
                <p class="text-sm text-gray-500">
                  {filtered().length} result{filtered().length !== 1 ? "s" : ""}
                </p>
                <select
                  value={sortKey()}
                  onChange={(e) => setSortKey(e.currentTarget.value as SortKey)}
                  class="rounded-lg border border-gray-300 px-3 py-1.5 text-sm text-gray-700 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="name">Name (A–Z)</option>
                  <option value="price-asc">Price: Low to High</option>
                  <option value="price-desc">Price: High to Low</option>
                  <option value="rating">Top Rated</option>
                </select>
              </div>

              <Show
                when={filtered().length > 0}
                fallback={
                  <div class="flex h-64 items-center justify-center rounded-xl border border-gray-200 bg-white">
                    <p class="text-sm text-gray-500">No products match your filters.</p>
                  </div>
                }
              >
                <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
                  <For each={filtered()}>
                    {(product) => (
                      <A
                        href={`/products/${product.id}`}
                        class="block bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow overflow-hidden border border-gray-100"
                      >
                        <img
                          src={product.image_url}
                          alt={product.name}
                          width={400}
                          height={300}
                          class="w-full h-40 object-cover"
                          loading="lazy"
                        />
                        <div class="p-4">
                          <span class="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full">
                            {product.category}
                          </span>
                          <h2 class="mt-2 text-sm font-semibold text-gray-900 line-clamp-2">
                            {product.name}
                          </h2>
                          <div class="mt-2 flex items-center justify-between">
                            <span class="text-base font-bold text-gray-900">
                              ${product.price.toFixed(2)}
                            </span>
                            <span class="text-sm text-gray-500">
                              ★ {product.rating.toFixed(1)}
                            </span>
                          </div>
                        </div>
                      </A>
                    )}
                  </For>
                </div>
              </Show>
            </div>
          </div>
        </Show>
      </Show>
    </div>
  );
}

// packages/nextjs-pages/pages/filter.tsx
"use client";

import { useState, useEffect, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import Layout from "@/components/Layout";
import type { Product, Category, ApiResponse } from "@benchmark/data";

const API_URL = process.env["NEXT_PUBLIC_API_URL"] ?? "http://localhost:3000";

const CATEGORIES: Category[] = [
  "Electronics",
  "Clothing",
  "Books",
  "Home & Garden",
  "Sports",
  "Toys",
  "Food & Beverage",
  "Beauty",
];

export default function FilterPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCategories, setSelectedCategories] = useState<Set<Category>>(
    new Set()
  );
  const [maxPrice, setMaxPrice] = useState(1000);
  const [minRating, setMinRating] = useState(0);

  useEffect(() => {
    async function loadProducts() {
      try {
        const res = await fetch(`${API_URL}/products`);
        const json = (await res.json()) as ApiResponse<Product[]>;
        setProducts(json.data);
      } catch (err) {
        console.error("Failed to load products:", err);
      } finally {
        setLoading(false);
      }
    }
    void loadProducts();
  }, []);

  const maxProductPrice = useMemo(() => {
    if (products.length === 0) return 1000;
    return Math.ceil(Math.max(...products.map((p) => p.price)));
  }, [products]);

  const filtered = useMemo(() => {
    return products.filter((p) => {
      if (selectedCategories.size > 0 && !selectedCategories.has(p.category)) {
        return false;
      }
      if (p.price > maxPrice) return false;
      if (p.rating < minRating) return false;
      return true;
    });
  }, [products, selectedCategories, maxPrice, minRating]);

  function toggleCategory(cat: Category) {
    setSelectedCategories((prev) => {
      const next = new Set(prev);
      if (next.has(cat)) {
        next.delete(cat);
      } else {
        next.add(cat);
      }
      return next;
    });
  }

  return (
    <Layout>
      <h1 className="text-3xl font-bold text-neutral-900 mb-6">
        Filter Products
      </h1>

      <div className="flex gap-8">
        {/* Sidebar filters */}
        <aside className="w-64 shrink-0">
          <div className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-5 space-y-6">
            {/* Category filter */}
            <div>
              <h2 className="text-sm font-semibold text-neutral-900 uppercase tracking-wide mb-3">
                Category
              </h2>
              <div className="space-y-2">
                {CATEGORIES.map((cat) => (
                  <label
                    key={cat}
                    className="flex items-center gap-2 cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={selectedCategories.has(cat)}
                      onChange={() => toggleCategory(cat)}
                      className="w-4 h-4 accent-brand-600"
                    />
                    <span className="text-sm text-neutral-700">{cat}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Price range filter */}
            <div>
              <h2 className="text-sm font-semibold text-neutral-900 uppercase tracking-wide mb-3">
                Max Price: ${maxPrice}
              </h2>
              <input
                type="range"
                min={0}
                max={maxProductPrice}
                value={maxPrice}
                onChange={(e) => setMaxPrice(Number(e.target.value))}
                className="w-full accent-brand-600"
              />
              <div className="flex justify-between text-xs text-neutral-500 mt-1">
                <span>$0</span>
                <span>${maxProductPrice}</span>
              </div>
            </div>

            {/* Rating filter */}
            <div>
              <h2 className="text-sm font-semibold text-neutral-900 uppercase tracking-wide mb-3">
                Min Rating: {minRating.toFixed(1)} ★
              </h2>
              <input
                type="range"
                min={0}
                max={5}
                step={0.5}
                value={minRating}
                onChange={(e) => setMinRating(Number(e.target.value))}
                className="w-full accent-brand-600"
              />
              <div className="flex justify-between text-xs text-neutral-500 mt-1">
                <span>Any</span>
                <span>5★</span>
              </div>
            </div>

            {/* Reset */}
            <button
              onClick={() => {
                setSelectedCategories(new Set());
                setMaxPrice(maxProductPrice);
                setMinRating(0);
              }}
              className="w-full text-sm font-medium text-brand-600 border border-brand-300 px-4 py-2 rounded-[var(--radius-button)] hover:bg-brand-50 transition-colors"
            >
              Reset Filters
            </button>
          </div>
        </aside>

        {/* Product grid */}
        <div className="flex-1">
          {loading ? (
            <div className="flex items-center justify-center h-48">
              <span className="text-neutral-500">Loading products…</span>
            </div>
          ) : (
            <>
              <p className="text-sm text-neutral-500 mb-4">
                {filtered.length} product{filtered.length !== 1 ? "s" : ""}{" "}
                found
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {filtered.map((product) => (
                  <article
                    key={product.id}
                    className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] hover:shadow-[var(--shadow-card-hover)] transition-shadow overflow-hidden flex flex-col"
                  >
                    <Link href={`/products/${product.id}`} className="block">
                      <div className="aspect-square bg-neutral-100 overflow-hidden">
                        <Image
                          src={product.image_url}
                          alt={product.name}
                          width={400}
                          height={400}
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </Link>
                    <div className="p-4 flex flex-col flex-1">
                      <span className="text-xs font-medium text-brand-600 uppercase tracking-wide mb-1">
                        {product.category}
                      </span>
                      <h2 className="text-sm font-semibold text-neutral-900 line-clamp-2 mb-2 flex-1">
                        <Link href={`/products/${product.id}`}>
                          {product.name}
                        </Link>
                      </h2>
                      <div className="flex items-center gap-1 mb-2">
                        <span className="text-warning text-sm">
                          {"★".repeat(Math.round(product.rating))}
                          {"☆".repeat(5 - Math.round(product.rating))}
                        </span>
                        <span className="text-xs text-neutral-500">
                          ({product.rating.toFixed(1)})
                        </span>
                      </div>
                      <div className="flex items-center justify-between mt-auto pt-2 border-t border-neutral-100">
                        <span className="text-lg font-bold text-neutral-900">
                          ${product.price.toFixed(2)}
                        </span>
                        <Link
                          href={`/products/${product.id}`}
                          className="text-xs font-medium bg-brand-600 text-white px-3 py-1.5 rounded-[var(--radius-button)] hover:bg-brand-700 transition-colors"
                        >
                          View
                        </Link>
                      </div>
                    </div>
                  </article>
                ))}
              </div>
            </>
          )}
        </div>
      </div>
    </Layout>
  );
}
