// packages/solidstart/src/routes/products/[id].tsx
import { createAsync, cache, useParams } from "@solidjs/router";
import { Show, Suspense, onMount } from "solid-js";
import type { ApiResponse, Product } from "@benchmark/data";
import { A } from "@solidjs/router";
import { addToCart, hydrateCart } from "../../stores/cart";

const API_URL = import.meta.env["VITE_API_URL"] ?? "http://localhost:3000";

const getProduct = cache(async (id: string) => {
  "use server";
  try {
    const res = await fetch(`${API_URL}/products/${id}`);
    if (!res.ok) return null;
    const json = (await res.json()) as ApiResponse<Product>;
    return json.data;
  } catch {
    return null;
  }
}, "product");

export const route = {
  preload: ({ params }: { params: { id: string } }) =>
    getProduct(params.id),
};

export default function ProductDetailPage() {
  const params = useParams<{ id: string }>();
  const product = createAsync(() => getProduct(params.id));
  onMount(() => hydrateCart());

  return (
    <Suspense
      fallback={
        <div class="flex h-64 items-center justify-center">
          <div class="h-8 w-8 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" />
        </div>
      }
    >
      <Show
        when={product()}
        fallback={
          <div class="text-center py-16">
            <h1 class="text-2xl font-bold text-gray-900">Product not found</h1>
            <A href="/" class="mt-4 inline-block text-blue-600 hover:underline">
              ← Back to products
            </A>
          </div>
        }
      >
        {(p) => (
          <div class="max-w-4xl mx-auto">
            <A
              href="/"
              class="inline-flex items-center gap-1 text-sm text-blue-600 hover:underline mb-6"
            >
              ← Back to products
            </A>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div class="rounded-xl overflow-hidden bg-gray-100">
                <img
                  src={p().image_url}
                  alt={p().name}
                  width={600}
                  height={450}
                  class="w-full h-auto object-cover"
                />
              </div>
              <div class="flex flex-col gap-4">
                <span class="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full w-fit">
                  {p().category}
                </span>
                <h1 class="text-2xl font-bold text-gray-900">{p().name}</h1>
                <p class="text-gray-600 text-sm leading-relaxed">
                  {p().description}
                </p>
                <div class="flex items-center gap-4">
                  <span class="text-3xl font-bold text-gray-900">
                    ${p().price.toFixed(2)}
                  </span>
                  <span class="text-sm text-gray-500">
                    ★ {p().rating.toFixed(1)}
                  </span>
                </div>
                <div class="flex flex-wrap gap-2 mt-2">
                  {p()
                    .tags.map((tag) => (
                      <span class="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded-full">
                        {tag}
                      </span>
                    ))}
                </div>
                <p class="text-sm font-medium text-gray-700">
                  {p().stock > 0 ? (
                    <span class="text-green-600">{p().stock} in stock</span>
                  ) : (
                    <span class="text-red-600">Out of stock</span>
                  )}
                </p>
                <button
                  disabled={p().stock === 0}
                  onClick={() => {
                    addToCart(p());
                  }}
                  class="mt-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-medium text-white hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                >
                  {p().stock > 0 ? "Add to Cart" : "Out of Stock"}
                </button>
              </div>
            </div>
          </div>
        )}
      </Show>
    </Suspense>
  );
}

// packages/nuxt/pages/products/[id].vue
<script setup lang="ts">
import type { Product } from '@benchmark/data'

interface ApiResponse {
  data: Product
}

const route = useRoute()
const config = useRuntimeConfig()
const id = route.params['id'] as string

const { data, error } = await useFetch<ApiResponse>(`/products/${id}`, {
  baseURL: config.public.apiUrl,
})

const product = computed(() => data.value?.data ?? null)

const cartStore = useCartStore()

function addToCart() {
  if (product.value) {
    cartStore.addItem(product.value)
  }
}
</script>

<template>
  <div>
    <NuxtLink to="/" class="text-brand-600 hover:underline text-sm mb-6 inline-block">
      &larr; Back to products
    </NuxtLink>

    <div v-if="error" class="text-danger font-medium p-4 bg-red-50 rounded-lg">
      Error loading product: {{ error.message }}
    </div>

    <div v-else-if="!product" class="text-neutral-500 text-center py-16">
      Product not found.
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-12">
      <!-- Image -->
      <div class="rounded-[var(--radius-card)] overflow-hidden bg-neutral-100 aspect-[4/3]">
        <NuxtImg
          :src="product.image_url"
          :alt="product.name"
          class="w-full h-full object-cover"
          width="800"
          height="600"
        />
      </div>

      <!-- Details -->
      <div class="flex flex-col gap-4">
        <span class="inline-block text-sm font-medium text-brand-600 bg-brand-50 px-3 py-1 rounded-[var(--radius-badge)] w-fit">
          {{ product.category }}
        </span>
        <h1 class="text-3xl font-bold text-neutral-900">{{ product.name }}</h1>
        <p class="text-neutral-600 leading-relaxed">{{ product.description }}</p>

        <div class="flex items-center gap-4 mt-2">
          <span class="text-3xl font-bold text-neutral-900">${{ product.price.toFixed(2) }}</span>
          <span class="text-neutral-500">★ {{ product.rating.toFixed(1) }} rating</span>
        </div>

        <div class="text-sm text-neutral-500">
          {{ product.stock > 0 ? `${product.stock} in stock` : 'Out of stock' }}
        </div>

        <div class="flex flex-wrap gap-2 mt-2">
          <span
            v-for="tag in product.tags"
            :key="tag"
            class="text-xs bg-neutral-100 text-neutral-600 px-2 py-1 rounded-[var(--radius-badge)]"
          >
            {{ tag }}
          </span>
        </div>

        <button
          :disabled="product.stock === 0"
          class="mt-4 bg-brand-600 hover:bg-brand-700 text-white font-semibold px-8 py-3 rounded-[var(--radius-button)] transition-colors disabled:opacity-50 disabled:cursor-not-allowed w-fit"
          @click="addToCart"
        >
          Add to Cart
        </button>
      </div>
    </div>
  </div>
</template>
