// packages/nextjs-pages/pages/products/[id].tsx
import type { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Image from "next/image";
import Link from "next/link";
import Layout from "@/components/Layout";
import type { Product, ApiResponse } from "@benchmark/data";

const API_URL = process.env["API_URL"] ?? "http://localhost:3000";

export const getServerSideProps = (async (context) => {
  const { id } = context.params as { id: string };
  try {
    const res = await fetch(`${API_URL}/products/${id}`);
    if (!res.ok) return { notFound: true };
    const json = (await res.json()) as ApiResponse<Product>;
    return { props: { product: json.data } };
  } catch {
    return { notFound: true };
  }
}) satisfies GetServerSideProps<{ product: Product }>;

type Props = InferGetServerSidePropsType<typeof getServerSideProps>;

export default function ProductDetailPage({ product }: Props) {
  return (
    <Layout>
      <div className="mb-4">
        <Link
          href="/"
          className="text-sm text-brand-600 hover:text-brand-700 font-medium"
        >
          ← Back to Products
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="aspect-square bg-neutral-100 rounded-[var(--radius-card)] overflow-hidden">
          <Image
            src={product.image_url}
            alt={product.name}
            width={600}
            height={600}
            className="w-full h-full object-cover"
            priority
          />
        </div>

        <div className="flex flex-col">
          <span className="text-sm font-medium text-brand-600 uppercase tracking-wide mb-2">
            {product.category}
          </span>
          <h1 className="text-3xl font-bold text-neutral-900 mb-4">
            {product.name}
          </h1>

          <div className="flex items-center gap-2 mb-4">
            <span className="text-warning text-lg">
              {"★".repeat(Math.round(product.rating))}
              {"☆".repeat(5 - Math.round(product.rating))}
            </span>
            <span className="text-sm text-neutral-500">
              {product.rating.toFixed(1)} rating
            </span>
          </div>

          <p className="text-neutral-600 leading-relaxed mb-6">
            {product.description}
          </p>

          <div className="flex flex-wrap gap-2 mb-6">
            {product.tags.map((tag) => (
              <span
                key={tag}
                className="text-xs font-medium bg-neutral-100 text-neutral-600 px-2 py-1 rounded-[var(--radius-badge)]"
              >
                {tag}
              </span>
            ))}
          </div>

          <div className="mt-auto">
            <div className="flex items-center justify-between mb-4">
              <span className="text-4xl font-bold text-neutral-900">
                ${product.price.toFixed(2)}
              </span>
              <span
                className={`text-sm font-medium px-3 py-1 rounded-[var(--radius-badge)] ${
                  product.stock > 0
                    ? "bg-success/10 text-success"
                    : "bg-danger/10 text-danger"
                }`}
              >
                {product.stock > 0
                  ? `${product.stock} in stock`
                  : "Out of stock"}
              </span>
            </div>

            <Link
              href="/cart"
              className="block w-full text-center font-medium bg-brand-600 text-white px-6 py-3 rounded-[var(--radius-button)] hover:bg-brand-700 transition-colors"
            >
              Add to Cart
            </Link>
          </div>
        </div>
      </div>
    </Layout>
  );
}

// packages/solidstart/src/routes/products/[id].tsx
import { createAsync, cache, useParams } from "@solidjs/router";
import { Show, Suspense, onMount } from "solid-js";
import type { ApiResponse, Product } from "@benchmark/data";
import { A } from "@solidjs/router";
import { addToCart, hydrateCart } from "../../stores/cart";

const API_URL = import.meta.env["VITE_API_URL"] ?? "http://localhost:3000";

const getProduct = cache(async (id: string) => {
  "use server";
  try {
    const res = await fetch(`${API_URL}/products/${id}`);
    if (!res.ok) return null;
    const json = (await res.json()) as ApiResponse<Product>;
    return json.data;
  } catch {
    return null;
  }
}, "product");

export const route = {
  preload: ({ params }: { params: { id: string } }) =>
    getProduct(params.id),
};

export default function ProductDetailPage() {
  const params = useParams<{ id: string }>();
  const product = createAsync(() => getProduct(params.id));
  onMount(() => hydrateCart());

  return (
    <Suspense
      fallback={
        <div class="flex h-64 items-center justify-center">
          <div class="h-8 w-8 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" />
        </div>
      }
    >
      <Show
        when={product()}
        fallback={
          <div class="text-center py-16">
            <h1 class="text-2xl font-bold text-gray-900">Product not found</h1>
            <A href="/" class="mt-4 inline-block text-blue-600 hover:underline">
              ← Back to products
            </A>
          </div>
        }
      >
        {(p) => (
          <div class="max-w-4xl mx-auto">
            <A
              href="/"
              class="inline-flex items-center gap-1 text-sm text-blue-600 hover:underline mb-6"
            >
              ← Back to products
            </A>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div class="rounded-xl overflow-hidden bg-gray-100">
                <img
                  src={p().image_url}
                  alt={p().name}
                  width={600}
                  height={450}
                  class="w-full h-auto object-cover"
                />
              </div>
              <div class="flex flex-col gap-4">
                <span class="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full w-fit">
                  {p().category}
                </span>
                <h1 class="text-2xl font-bold text-gray-900">{p().name}</h1>
                <p class="text-gray-600 text-sm leading-relaxed">
                  {p().description}
                </p>
                <div class="flex items-center gap-4">
                  <span class="text-3xl font-bold text-gray-900">
                    ${p().price.toFixed(2)}
                  </span>
                  <span class="text-sm text-gray-500">
                    ★ {p().rating.toFixed(1)}
                  </span>
                </div>
                <div class="flex flex-wrap gap-2 mt-2">
                  {p()
                    .tags.map((tag) => (
                      <span class="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded-full">
                        {tag}
                      </span>
                    ))}
                </div>
                <p class="text-sm font-medium text-gray-700">
                  {p().stock > 0 ? (
                    <span class="text-green-600">{p().stock} in stock</span>
                  ) : (
                    <span class="text-red-600">Out of stock</span>
                  )}
                </p>
                <button
                  disabled={p().stock === 0}
                  onClick={() => {
                    addToCart(p());
                  }}
                  class="mt-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-medium text-white hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                >
                  {p().stock > 0 ? "Add to Cart" : "Out of Stock"}
                </button>
              </div>
            </div>
          </div>
        )}
      </Show>
    </Suspense>
  );
}
