// packages/nextjs-pages/pages/cart.tsx
import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import Layout from "@/components/Layout";
import type { Product, CartItem, ApiResponse } from "@benchmark/data";

const API_URL = process.env["NEXT_PUBLIC_API_URL"] ?? "http://localhost:3000";

export default function CartPage() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [addId, setAddId] = useState<string>("");
  const [searchResults, setSearchResults] = useState<Product[]>([]);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    async function loadProducts() {
      try {
        const res = await fetch(`${API_URL}/products`);
        const json = (await res.json()) as ApiResponse<Product[]>;
        setProducts(json.data);
      } catch (err) {
        console.error("Failed to load products:", err);
      } finally {
        setLoading(false);
      }
    }
    void loadProducts();
  }, []);

  useEffect(() => {
    if (searchQuery.trim().length === 0) {
      setSearchResults([]);
      return;
    }
    const q = searchQuery.toLowerCase();
    setSearchResults(
      products
        .filter(
          (p) =>
            p.name.toLowerCase().includes(q) ||
            p.category.toLowerCase().includes(q)
        )
        .slice(0, 5)
    );
  }, [searchQuery, products]);

  function addToCart(product: Product) {
    setCart((prev) => {
      const existing = prev.find((item) => item.product.id === product.id);
      if (existing) {
        return prev.map((item) =>
          item.product.id === product.id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        );
      }
      return [...prev, { product, quantity: 1 }];
    });
    setSearchQuery("");
    setSearchResults([]);
    setAddId("");
  }

  function removeFromCart(productId: number) {
    setCart((prev) => prev.filter((item) => item.product.id !== productId));
  }

  function updateQuantity(productId: number, delta: number) {
    setCart((prev) =>
      prev
        .map((item) =>
          item.product.id === productId
            ? { ...item, quantity: item.quantity + delta }
            : item
        )
        .filter((item) => item.quantity > 0)
    );
  }

  const subtotal = cart.reduce(
    (sum, item) => sum + item.product.price * item.quantity,
    0
  );

  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);

  return (
    <Layout cartCount={totalItems}>
      <h1 className="text-3xl font-bold text-neutral-900 mb-6">
        Cart ({totalItems} item{totalItems !== 1 ? "s" : ""})
      </h1>

      {/* Add product search */}
      <div className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-5 mb-6">
        <h2 className="text-sm font-semibold text-neutral-700 mb-3">
          Add Product
        </h2>
        <div className="relative">
          <input
            type="text"
            placeholder="Search products by name or category…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            disabled={loading}
            className="w-full border border-neutral-300 rounded-[var(--radius-button)] px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
          />
          {searchResults.length > 0 && (
            <ul className="absolute top-full left-0 right-0 mt-1 bg-white border border-neutral-200 rounded-[var(--radius-card)] shadow-[var(--shadow-dropdown)] z-20">
              {searchResults.map((product) => (
                <li key={product.id}>
                  <button
                    onClick={() => addToCart(product)}
                    className="w-full text-left px-4 py-2 text-sm hover:bg-neutral-50 flex items-center gap-3"
                  >
                    <span className="font-medium text-neutral-900 truncate">
                      {product.name}
                    </span>
                    <span className="text-neutral-500 shrink-0">
                      ${product.price.toFixed(2)}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      {cart.length === 0 ? (
        <div className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-12 text-center">
          <p className="text-neutral-500 mb-4">Your cart is empty.</p>
          <Link
            href="/"
            className="inline-block text-sm font-medium bg-brand-600 text-white px-6 py-2 rounded-[var(--radius-button)] hover:bg-brand-700 transition-colors"
          >
            Browse Products
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Cart items */}
          <div className="lg:col-span-2 space-y-4">
            {cart.map((item) => (
              <div
                key={item.product.id}
                className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-4 flex gap-4"
              >
                <div className="w-20 h-20 bg-neutral-100 rounded-lg overflow-hidden shrink-0">
                  <Image
                    src={item.product.image_url}
                    alt={item.product.name}
                    width={80}
                    height={80}
                    className="w-full h-full object-cover"
                  />
                </div>

                <div className="flex-1 min-w-0">
                  <h3 className="text-sm font-semibold text-neutral-900 truncate">
                    {item.product.name}
                  </h3>
                  <p className="text-xs text-neutral-500 mt-0.5">
                    {item.product.category}
                  </p>
                  <p className="text-sm font-bold text-neutral-900 mt-1">
                    ${item.product.price.toFixed(2)}
                  </p>
                </div>

                <div className="flex flex-col items-end justify-between shrink-0">
                  <button
                    onClick={() => removeFromCart(item.product.id)}
                    className="text-danger text-xs hover:underline"
                  >
                    Remove
                  </button>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => updateQuantity(item.product.id, -1)}
                      className="w-7 h-7 flex items-center justify-center border border-neutral-300 rounded text-sm hover:bg-neutral-50"
                    >
                      −
                    </button>
                    <span className="text-sm font-medium w-6 text-center">
                      {item.quantity}
                    </span>
                    <button
                      onClick={() => updateQuantity(item.product.id, 1)}
                      className="w-7 h-7 flex items-center justify-center border border-neutral-300 rounded text-sm hover:bg-neutral-50"
                    >
                      +
                    </button>
                  </div>

                  <p className="text-sm font-semibold text-neutral-900">
                    ${(item.product.price * item.quantity).toFixed(2)}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* Order summary */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-5 sticky top-24">
              <h2 className="text-lg font-semibold text-neutral-900 mb-4">
                Order Summary
              </h2>

              <div className="space-y-2 mb-4">
                {cart.map((item) => (
                  <div key={item.product.id} className="flex justify-between text-sm">
                    <span className="text-neutral-600 truncate pr-2">
                      {item.product.name} × {item.quantity}
                    </span>
                    <span className="text-neutral-900 shrink-0">
                      ${(item.product.price * item.quantity).toFixed(2)}
                    </span>
                  </div>
                ))}
              </div>

              <div className="border-t border-neutral-200 pt-4">
                <div className="flex justify-between text-base font-bold">
                  <span>Subtotal</span>
                  <span>${subtotal.toFixed(2)}</span>
                </div>
              </div>

              <button
                className="mt-5 w-full bg-brand-600 text-white font-medium py-3 rounded-[var(--radius-button)] hover:bg-brand-700 transition-colors"
                onClick={() => alert("Checkout is out of scope for this benchmark.")}
              >
                Checkout
              </button>

              <button
                onClick={() => setCart([])}
                className="mt-2 w-full text-sm text-neutral-500 hover:text-danger transition-colors"
              >
                Clear Cart
              </button>
            </div>
          </div>
        </div>
      )}
    </Layout>
  );
}

// packages/solidstart/src/routes/cart.tsx
import { createSignal, createMemo, For, Show, onMount } from "solid-js";
import { createStore, produce } from "solid-js/store";
import type { Product, CartItem, ApiResponse } from "@benchmark/data";
import { A } from "@solidjs/router";

const API_URL = import.meta.env["VITE_API_URL"] ?? "http://localhost:3000";

interface CartState {
  items: CartItem[];
}

export default function CartPage() {
  const [cartStore, setCartStore] = createStore<CartState>({ items: [] });
  const [allProducts, setAllProducts] = createSignal<Product[]>([]);
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal<string | null>(null);

  onMount(async () => {
    try {
      const res = await fetch(`${API_URL}/products`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = (await res.json()) as ApiResponse<Product[]>;
      setAllProducts(json.data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load products");
    } finally {
      setLoading(false);
    }
  });

  const addToCart = (product: Product) => {
    setCartStore(
      produce((state) => {
        const existing = state.items.find((i) => i.product.id === product.id);
        if (existing) {
          existing.quantity += 1;
        } else {
          state.items.push({ product, quantity: 1 });
        }
      })
    );
  };

  const removeFromCart = (productId: number) => {
    setCartStore(
      produce((state) => {
        state.items = state.items.filter((i) => i.product.id !== productId);
      })
    );
  };

  const updateQuantity = (productId: number, quantity: number) => {
    if (quantity <= 0) {
      removeFromCart(productId);
      return;
    }
    setCartStore(
      produce((state) => {
        const item = state.items.find((i) => i.product.id === productId);
        if (item) {
          item.quantity = quantity;
        }
      })
    );
  };

  const totalItems = createMemo(() =>
    cartStore.items.reduce((sum, item) => sum + item.quantity, 0)
  );

  const totalPrice = createMemo(() =>
    cartStore.items.reduce(
      (sum, item) => sum + item.product.price * item.quantity,
      0
    )
  );

  return (
    <div>
      <h1 class="text-3xl font-bold text-gray-900 mb-8">
        Shopping Cart{" "}
        <Show when={totalItems() > 0}>
          <span class="text-lg font-normal text-gray-500">
            ({totalItems()} item{totalItems() !== 1 ? "s" : ""})
          </span>
        </Show>
      </h1>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Cart Items */}
        <div class="lg:col-span-2">
          <Show
            when={cartStore.items.length > 0}
            fallback={
              <div class="rounded-xl border border-gray-200 bg-white p-8 text-center">
                <p class="text-gray-500 mb-4">Your cart is empty.</p>
                <A
                  href="/"
                  class="inline-block rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 transition-colors"
                >
                  Browse Products
                </A>
              </div>
            }
          >
            <div class="flex flex-col gap-4">
              <For each={cartStore.items}>
                {(item) => (
                  <div class="flex gap-4 rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
                    <img
                      src={item.product.image_url}
                      alt={item.product.name}
                      width={96}
                      height={96}
                      class="w-24 h-24 object-cover rounded-lg flex-shrink-0"
                    />
                    <div class="flex-1 min-w-0">
                      <h3 class="font-semibold text-gray-900 text-sm line-clamp-2">
                        {item.product.name}
                      </h3>
                      <p class="text-xs text-gray-500 mt-1">{item.product.category}</p>
                      <p class="text-base font-bold text-gray-900 mt-2">
                        ${item.product.price.toFixed(2)}
                      </p>
                    </div>
                    <div class="flex flex-col items-end gap-2 flex-shrink-0">
                      <button
                        onClick={() => removeFromCart(item.product.id)}
                        class="text-xs text-red-500 hover:text-red-700 transition-colors"
                      >
                        Remove
                      </button>
                      <div class="flex items-center gap-2">
                        <button
                          onClick={() =>
                            updateQuantity(item.product.id, item.quantity - 1)
                          }
                          class="w-7 h-7 rounded-full border border-gray-300 flex items-center justify-center text-gray-600 hover:bg-gray-50 transition-colors text-sm font-medium"
                        >
                          −
                        </button>
                        <span class="text-sm font-medium text-gray-900 w-4 text-center">
                          {item.quantity}
                        </span>
                        <button
                          onClick={() =>
                            updateQuantity(item.product.id, item.quantity + 1)
                          }
                          class="w-7 h-7 rounded-full border border-gray-300 flex items-center justify-center text-gray-600 hover:bg-gray-50 transition-colors text-sm font-medium"
                        >
                          +
                        </button>
                      </div>
                      <p class="text-sm font-semibold text-gray-900">
                        ${(item.product.price * item.quantity).toFixed(2)}
                      </p>
                    </div>
                  </div>
                )}
              </For>
            </div>
          </Show>
        </div>

        {/* Summary + Add Products */}
        <div class="flex flex-col gap-4">
          {/* Order Summary */}
          <Show when={cartStore.items.length > 0}>
            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
              <h2 class="text-base font-semibold text-gray-900 mb-4">
                Order Summary
              </h2>
              <div class="flex justify-between text-sm text-gray-600 mb-2">
                <span>Items ({totalItems()})</span>
                <span>${totalPrice().toFixed(2)}</span>
              </div>
              <div class="border-t border-gray-200 pt-3 mt-3">
                <div class="flex justify-between font-bold text-gray-900">
                  <span>Total</span>
                  <span>${totalPrice().toFixed(2)}</span>
                </div>
              </div>
              <button class="mt-4 w-full rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-700 transition-colors">
                Proceed to Checkout
              </button>
            </div>
          </Show>

          {/* Products to add */}
          <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
            <h2 class="text-base font-semibold text-gray-900 mb-4">
              Add Products
            </h2>
            <Show
              when={!loading()}
              fallback={
                <div class="flex h-16 items-center justify-center">
                  <div class="h-5 w-5 animate-spin rounded-full border-2 border-blue-200 border-t-blue-600" />
                </div>
              }
            >
              <Show when={!error()} fallback={
                <p class="text-sm text-red-600">{error()}</p>
              }>
                <div class="flex flex-col gap-2 max-h-80 overflow-y-auto">
                  <For each={allProducts().slice(0, 20)}>
                    {(product) => (
                      <div class="flex items-center justify-between gap-2 py-1.5 border-b border-gray-100 last:border-0">
                        <div class="flex-1 min-w-0">
                          <p class="text-xs font-medium text-gray-800 line-clamp-1">
                            {product.name}
                          </p>
                          <p class="text-xs text-gray-500">
                            ${product.price.toFixed(2)}
                          </p>
                        </div>
                        <button
                          onClick={() => addToCart(product)}
                          class="flex-shrink-0 rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-600 hover:bg-blue-100 transition-colors"
                        >
                          Add
                        </button>
                      </div>
                    )}
                  </For>
                </div>
              </Show>
            </Show>
          </div>
        </div>
      </div>
    </div>
  );
}
