// packages/nextjs-pages/pages/index.tsx
import type { GetStaticProps, InferGetStaticPropsType } from "next";
import Image from "next/image";
import Link from "next/link";
import Layout from "@/components/Layout";
import type { Product } from "@benchmark/data";
import { products } from "@benchmark/data";

export const getStaticProps = (() => {
  return { props: { products } };
}) satisfies GetStaticProps<{ products: Product[] }>;

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export default function ProductListingPage({ products }: Props) {
  return (
    <Layout>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-3xl font-bold text-neutral-900">All Products</h1>
        <span className="text-sm text-neutral-500">
          Showing {products.length} products
        </span>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {products.map((product) => (
          <article
            key={product.id}
            className="bg-white rounded-[var(--radius-card)] shadow-[var(--shadow-card)] hover:shadow-[var(--shadow-card-hover)] transition-shadow overflow-hidden flex flex-col"
          >
            <Link href={`/products/${product.id}`} className="block">
              <div className="aspect-square bg-neutral-100 overflow-hidden">
                <Image
                  src={product.image_url}
                  alt={product.name}
                  width={400}
                  height={400}
                  className="w-full h-full object-cover"
                />
              </div>
            </Link>
            <div className="p-4 flex flex-col flex-1">
              <span className="text-xs font-medium text-brand-600 uppercase tracking-wide mb-1">
                {product.category}
              </span>
              <h2 className="text-sm font-semibold text-neutral-900 line-clamp-2 mb-2 flex-1">
                <Link href={`/products/${product.id}`}>{product.name}</Link>
              </h2>
              <div className="flex items-center gap-1 mb-2">
                <span className="text-warning text-sm">
                  {"★".repeat(Math.round(product.rating))}
                  {"☆".repeat(5 - Math.round(product.rating))}
                </span>
                <span className="text-xs text-neutral-500">
                  ({product.rating.toFixed(1)})
                </span>
              </div>
              <div className="flex items-center justify-between mt-auto pt-2 border-t border-neutral-100">
                <span className="text-lg font-bold text-neutral-900">
                  ${product.price.toFixed(2)}
                </span>
                <Link
                  href={`/products/${product.id}`}
                  className="text-xs font-medium bg-brand-600 text-white px-3 py-1.5 rounded-[var(--radius-button)] hover:bg-brand-700 transition-colors"
                >
                  View
                </Link>
              </div>
            </div>
          </article>
        ))}
      </div>
    </Layout>
  );
}

// packages/nuxt/pages/index.vue
<script setup lang="ts">
import type { Product } from '@benchmark/data'

interface ApiResponse {
  data: Product[]
}

const config = useRuntimeConfig()
const { data, error } = await useFetch<ApiResponse>('/products', {
  baseURL: config.public.apiUrl,
})

const products = computed(() => data.value?.data ?? [])
</script>

<template>
  <div>
    <div class="mb-8">
      <h2 class="text-3xl font-bold text-neutral-900">All Products</h2>
      <p class="text-neutral-500 mt-1">{{ products.length }} products available</p>
    </div>

    <div v-if="error" class="text-danger font-medium p-4 bg-red-50 rounded-lg">
      Error loading products: {{ error.message }}
    </div>

    <div
      v-else
      class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6"
    >
      <div
        v-for="product in products"
        :key="product.id"
        role="listitem"
        class="bg-surface rounded-[var(--radius-card)] shadow-card hover:shadow-card-hover transition-shadow overflow-hidden"
      >
        <a :href="`/products/${product.id}`" class="block">
          <div class="relative aspect-[4/3] overflow-hidden bg-neutral-100">
            <NuxtImg
              :src="product.image_url"
              :alt="product.name"
              class="w-full h-full object-cover"
              width="400"
              height="300"
              loading="lazy"
            />
          </div>
          <div class="p-4">
            <span class="inline-block text-xs font-medium text-brand-600 bg-brand-50 px-2 py-0.5 rounded-[var(--radius-badge)] mb-2">
              {{ product.category }}
            </span>
            <h3 class="font-semibold text-neutral-900 text-sm line-clamp-2 mb-1">{{ product.name }}</h3>
            <div class="flex items-center justify-between mt-2">
              <span class="font-bold text-neutral-900">${{ product.price.toFixed(2) }}</span>
              <span class="text-xs text-neutral-500">★ {{ product.rating.toFixed(1) }}</span>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</template>
